services:
  video-storage:
    image: video-storage
    build:
      context: ./video-storage
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT_NAME}
      - TENANT_ID=${TENANT_ID}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    restart: "no"

  video-streaming:
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=4000
    restart: "no"