FROM rust:1.89-bookworm AS base 
RUN apt-get update 
RUN apt-get upgrade -y
RUN apt-get install -y openssl pkg-config libssl-dev curl 
RUN rm -rf /var/lib/apt/lists/*
RUN cargo install --locked cargo-chef sccache 
ENV RUSTC_WRAPPER=sccache SCCACHE_DIR=/sccache

FROM base AS planner
WORKDIR /usr/src/app
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM base AS builder
WORKDIR /usr/src/app
COPY --from=planner /usr/src/app/recipe.json recipe.json
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    --mount=type=cache,target=$SCCACHE_DIR,sharing=locked \
    cargo chef cook --release --recipe-path recipe.json
CMD ["cargo", "run", "--release"]
