
FROM rust:1.89-bookworm AS base

WORKDIR /usr/src/app
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y openssl pkg-config libssl-dev
RUN cargo install --locked cargo-watch

CMD ["cargo", "watch", "-x", "run", "--poll"]